### ISSUE TITLE
Microflow seems to be in a loop

### ISSUE THREAD

**Issue by ghartwich** [RCatersels/CountryEnumeration#2]
Hi,
I would like to use the CountryEnumeration module to create a list of countries that I can use in my app. But when I run the application and click on the 'update country button' the application looks like it gets thrown in a loop. I have a screenshot of the console below:
![2015629-131442](https://cloud.githubusercontent.com/assets/9248651/8406871/50f0c4e8-1e61-11e5-9280-7d9e4b3d22c5.png)

Is there something i need to do to implement this correctly.
I'm usinf mx 5.16.1 and I downloaded the CountriesV5.mpk from github.

Thanks,
Gonzo

**Comment by RCatersels** [comment]
You should enable in the project settings / tab languages both Dutch, Netherlands and English, United States. Then it all works. I shall update the readme to reflect this. Thanks for pointing this out.

Regards,

Ronald

**Comment by ghartwich** [comment]
It works.

Thanks!
Gonzo

On 29 June 2015 at 14:25, Ronald Catersels notifications@github.com wrote:

> Closed #2 https://github.com/RCatersels/CountryEnumeration/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RCatersels/CountryEnumeration/issues/2#event-342941050
> .

## 

_Gonçalo Hartwich Nunes_

CEO | Hartwich Nunes bv
Tel. +31 (0)20 369 0203
Gsm. +31 (0)6 502 85530
ghn@hartwichnunes.com
www.hartwichnunes.com

Premium Partner F24 AG | www.f24.com
